"use client";

import { useMemo, useState } from "react";

type Proof = { label:string; value:string; note:string; url:string; source:string };
type Model = {
  id:string; name:string; maker:string; mark:string; tone:string; type:string;
  access:"API"|"Open weights"|"App + API"; best:string; limits:string; tags:string[];
  context:string; price:string; modalities:string; license:string; scores:Record<string,number>;
  keywords:string[]; link:string; proofs:Proof[];
};

const independent = "https://artificialanalysis.ai/models";
const models:Model[] = [
  {id:"gpt",name:"GPT-5.6 Sol",maker:"OpenAI",mark:"◎",tone:"lime",type:"Frontier reasoning",access:"App + API",context:"1.05M",price:"$5 / $30",modalities:"Text + image input",license:"Hosted",best:"Complex professional work, production coding, agents and computer use",limits:"Cloud-hosted; expensive output; no audio/video input; high-stakes facts still require verification.",tags:["Reasoning","Code","Vision","Tools"],scores:{medical:94,software:98,construction:94,creative:88,research:96},keywords:["code","software","agent","cyber","research","science","cad","construction","spreadsheet","computer use"],link:"https://developers.openai.com/api/docs/models/gpt-5.6-sol",proofs:[{label:"Professional workflows",value:"52.7%",note:"Agents’ Last Exam, max reasoning",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"Agentic browsing",value:"92.2%",note:"BrowseComp with Ultra",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"Published context",value:"1.05M",note:"128K maximum output",url:"https://developers.openai.com/api/docs/models/gpt-5.6-sol",source:"OpenAI API docs"}]},
  {id:"claude",name:"Claude Opus 4.8",maker:"Anthropic",mark:"A",tone:"coral",type:"Frontier reasoning",access:"App + API",context:"200K",price:"$5 / $25",modalities:"Text + image input",license:"Hosted",best:"Large codebases, long-form analysis, careful writing and document-heavy work",limits:"Cloud-hosted; premium price; usage limits and effort settings change latency and cost.",tags:["Reasoning","Code","Documents","Tools"],scores:{medical:92,software:97,construction:89,creative:96,research:95},keywords:["write","writing","legal","document","codebase","migration","analysis","financial","style","review"],link:"https://www.anthropic.com/news/claude-opus-4-8",proofs:[{label:"Coding",value:"88.6%",note:"SWE-bench Verified",url:"https://www.anthropic.com/system-cards",source:"Anthropic system card"},{label:"Browser use",value:"84.3%",note:"BrowseComp, single agent",url:"https://www.anthropic.com/system-cards",source:"Anthropic system card"},{label:"Self-critique",value:"4×",note:"Less likely than 4.7 to miss flaws in its code",url:"https://www.anthropic.com/news/claude-opus-4-8",source:"Anthropic · self-reported"}]},
  {id:"gemini",name:"Gemini 3.1 Pro",maker:"Google",mark:"✦",tone:"blue",type:"Multimodal frontier",access:"App + API",context:"1M",price:"See current rate card",modalities:"Text, image, audio + video",license:"Hosted",best:"Multimodal research, very long contexts, video/audio and Google workflows",limits:"Preview/stable variants change; 1M-context retrieval is materially weaker than at 128K in Google’s own MRCR result.",tags:["Vision","Video","Long context","Tools"],scores:{medical:95,software:94,construction:97,creative:91,research:98},keywords:["video","audio","image","diagram","drawing","blueprint","long document","google","multimodal","lecture"],link:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",proofs:[{label:"Science knowledge",value:"94.3%",note:"GPQA Diamond, no tools",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"},{label:"Abstract reasoning",value:"77.1%",note:"ARC-AGI-2 verified",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"},{label:"Multimodal",value:"80.5%",note:"MMMU-Pro, no tools",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"}]},
  {id:"llama",name:"Llama 4 Maverick",maker:"Meta",mark:"∞",tone:"violet",type:"Open-weight multimodal",access:"Open weights",context:"1M",price:"Infrastructure cost",modalities:"Text + image input",license:"Llama license",best:"Private deployments, customization and high-throughput multimodal applications",limits:"400B total parameters; self-hosting needs serious hardware, evaluation, security and safety engineering.",tags:["Open weights","Vision","Fine-tune"],scores:{medical:78,software:87,construction:85,creative:86,research:82},keywords:["private","on premise","self host","fine tune","customize","image","high volume"],link:"https://ai.meta.com/llama/get-started/",proofs:[{label:"Architecture",value:"17B active",note:"128 experts; 400B total parameters",url:"https://ai.meta.com/blog/llama-4-multimodal-intelligence/",source:"Meta release"},{label:"Availability",value:"Weights",note:"Direct and partner downloads",url:"https://ai.meta.com/llama/get-started/",source:"Meta documentation"},{label:"Input",value:"Multimodal",note:"Native text and image understanding",url:"https://ai.meta.com/blog/llama-4-multimodal-intelligence/",source:"Meta release"}]},
  {id:"deepseek",name:"DeepSeek R1",maker:"DeepSeek",mark:"D",tone:"blue",type:"Open reasoning",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text",license:"MIT (base R1)",best:"Math, reasoning research and cost-controlled open deployment",limits:"Older than today’s frontier; large local inference footprint; cited results use the authors’ own evaluation settings.",tags:["Reasoning","Math","Open weights"],scores:{medical:76,software:91,construction:79,creative:70,research:88},keywords:["math","equation","reasoning","open source","self host","research","codeforces"],link:"https://github.com/deepseek-ai/DeepSeek-R1",proofs:[{label:"Mathematics",value:"97.3%",note:"MATH-500 pass@1",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek technical report"},{label:"Coding",value:"65.9%",note:"LiveCodeBench pass@1-CoT",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek technical report"},{label:"License",value:"MIT",note:"Base R1; distilled models inherit base-model terms",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek repository"}]},
  {id:"mistral",name:"Mistral Medium 3.5",maker:"Mistral AI",mark:"M",tone:"coral",type:"Open multimodal agent",access:"Open weights",context:"256K",price:"$1.50 / $7.50",modalities:"Text + image / OCR",license:"Modified MIT",best:"Multilingual enterprise agents, coding, OCR and European deployment",limits:"Modified license needs review; ecosystem and independent evaluation coverage are smaller than for the largest labs.",tags:["Multilingual","Code","Open weights"],scores:{medical:82,software:92,construction:92,creative:86,research:86},keywords:["europe","european","multilingual","french","german","spanish","italian","ocr","document","private"],link:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",proofs:[{label:"Published context",value:"256K",note:"Frontier-class multimodal model",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral model card"},{label:"API price / 1M",value:"$1.50 / $7.50",note:"Input / output at publication",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral documentation"},{label:"Distribution",value:"Open weights",note:"Modified MIT license",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral model card"}]},
  {id:"qwen",name:"Qwen 3.6 35B-A3B",maker:"Alibaba Qwen",mark:"Q",tone:"violet",type:"Efficient open agent",access:"Open weights",context:"256K",price:"Infrastructure cost",modalities:"Text + image",license:"See model license",best:"Efficient agentic coding, multilingual and Chinese-language applications",limits:"Provider benchmarks include internal tests; licensing, regional compliance and deployment controls need review.",tags:["Open weights","Multilingual","Code"],scores:{medical:79,software:93,construction:84,creative:81,research:87},keywords:["chinese","multilingual","coding","efficient","small gpu","open source","agent","self host"],link:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",proofs:[{label:"Efficiency",value:"3B active",note:"35B total MoE parameters",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"},{label:"Context",value:"256K",note:"Published evaluation setting",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"},{label:"Availability",value:"Weights + API",note:"Hugging Face, ModelScope and Qwen Studio",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"}]},
  {id:"gemma",name:"Gemma 4 31B",maker:"Google",mark:"G",tone:"lime",type:"Efficient open multimodal",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text + image",license:"Gemma terms",best:"Private multimodal apps, research, tuning and consumer-workstation deployment",limits:"Smaller than frontier hosted models; Google warns of factual errors, bias and weak common-sense reasoning.",tags:["Open weights","Efficient","Fine-tune"],scores:{medical:84,software:90,construction:87,creative:84,research:85},keywords:["local","workstation","fine tune","open model","privacy","image","medical image","efficient"],link:"https://ai.google.dev/gemma/docs/core/model_card_4",proofs:[{label:"Knowledge",value:"85.2%",note:"MMLU-Pro, 31B instruction model",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"},{label:"Coding",value:"80.0%",note:"LiveCodeBench v6",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"},{label:"Medical multimodal",value:"61.3%",note:"MedXPertQA-MM",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"}]},
];

const domains=[
 {id:"medical",icon:"✚",name:"Medical & Health",desc:"Clinical support, research, operations",areas:["Clinical decision support","Medical imaging review","Patient education","Literature synthesis"],example:"Summarize a longitudinal record and flag missing evidence—always reviewed by a licensed clinician."},
 {id:"software",icon:"⌘",name:"Technology",desc:"Engineering, data, cybersecurity",areas:["Software engineering","Data analysis","Security review","Product research"],example:"Trace a failing integration test across a repository and propose a minimal, testable patch."},
 {id:"construction",icon:"▰",name:"Construction",desc:"Planning, design, field operations",areas:["Drawing & image review","Bid document analysis","Safety planning","Schedule risk"],example:"Compare plan sheets with a specification package and draft an RFI for inconsistencies."},
 {id:"creative",icon:"✦",name:"Creative Work",desc:"Writing, design, media",areas:["Campaign concepts","Editorial writing","Visual ideation","Video pre-production"],example:"Turn a product brief into three campaign territories with channel-ready copy."},
 {id:"research",icon:"◫",name:"Research & Education",desc:"Discovery, synthesis, tutoring",areas:["Evidence synthesis","Data interpretation","Adaptive tutoring","Grant research"],example:"Build a sourced evidence map that separates findings, uncertainty and open questions."},
];
const caution={medical:"Not a medical device or clinician. Use approved, privacy-safe systems; require expert review and source verification.",software:"Generated code can be insecure or subtly wrong. Run tests, scans and human review before deployment.",construction:"Never use unverified output as stamped design, code compliance or site-safety instruction.",creative:"Check originality, rights, brand voice and factual claims before publishing.",research:"Models can fabricate citations and flatten disagreement. Open every source and inspect the underlying evidence."};
const presets=["Review 300 pages of construction drawings and draft RFIs","Help a clinician summarize research on a rare disease","Refactor a TypeScript codebase with tests","Analyze interview videos and create a research brief"];
const priorityDefs=[{id:"privacy",label:"Private / self-hosted"},{id:"vision",label:"Images or video"},{id:"long",label:"Long documents"},{id:"cost",label:"Lower cost"},{id:"multilingual",label:"Multilingual"}];

function getRecommendations(text:string, priorities:string[]){
 const q=text.toLowerCase();
 const inferred = q.match(/medical|patient|clinical|disease|health|diagnos/) ? "medical" : q.match(/construct|drawing|blueprint|rfi|architect|site|building/) ? "construction" : q.match(/code|software|debug|typescript|python|api|cyber/) ? "software" : q.match(/write|campaign|creative|video|story|design/) ? "creative" : "research";
 return models.map(m=>{
   let score=m.scores[inferred]*.55+25;
   const hits=m.keywords.filter(k=>q.includes(k)); score+=Math.min(hits.length*5,15);
   if(priorities.includes("privacy")) score+=m.access==="Open weights"?18:-9;
   if(priorities.includes("vision")) score+=/image|video/.test(m.modalities.toLowerCase())?11:-7;
   if(priorities.includes("long")) score+=parseFloat(m.context)>=256?9:0;
   if(priorities.includes("cost")) score+=m.access==="Open weights"?8:m.id==="mistral"?9:-3;
   if(priorities.includes("multilingual")) score+=m.tags.includes("Multilingual")?12:m.id==="gemini"?7:0;
   const reasons=[`${m.scores[inferred]}/100 editorial fit for ${domains.find(d=>d.id===inferred)?.name}`,hits.length?`Matched: ${hits.slice(0,3).join(", ")}`:m.best,priorities.includes("privacy")&&m.access==="Open weights"?"Can be self-hosted for greater data control":""].filter(Boolean);
   return {m,score:Math.min(99,Math.round(score)),reasons,inferred};
 }).sort((a,b)=>b.score-a.score);
}

export default function Home(){
 const [domain,setDomain]=useState("medical"); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All");
 const [selected,setSelected]=useState<string[]>(["gpt","claude","gemini"]); const [useText,setUseText]=useState("");
 const [priorities,setPriorities]=useState<string[]>([]); const [results,setResults]=useState<ReturnType<typeof getRecommendations>|null>(null);
 const current=domains.find(d=>d.id===domain)!; const ranked=useMemo(()=>[...models].sort((a,b)=>b.scores[domain]-a.scores[domain]),[domain]);
 const visible=ranked.filter(m=>(filter==="All"||m.access===filter)&&`${m.name} ${m.maker} ${m.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
 const toggleCompare=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<4?[...s,id]:s);
 const runAdvisor=()=>{if(useText.trim().length<8)return;setResults(getRecommendations(useText,priorities));setTimeout(()=>document.getElementById("recommendation")?.scrollIntoView({behavior:"smooth",block:"center"}),50)};
 return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">M</span><span>Model Atlas</span></a><div className="navlinks"><a href="#advisor">Advisor</a><a href="#catalog">Evidence</a><a href="#compare">Compare</a></div><a className="nav-cta" href="#advisor">Describe your use <span>↘</span></a></nav>
  <section id="top" className="hero"><div className="eyebrow"><span>●</span> Evidence-led AI field guide · Research checked Aug 2026</div><h1>The right model<br/>for the <em>real work.</em></h1><p className="lede">Describe the job in plain language. Get a transparent recommendation, inspect the evidence, and compare the tradeoffs before you commit.</p><div className="hero-actions"><a href="#advisor" className="primary">Ask the model advisor <span>→</span></a><a href="#catalog" className="text-link">Inspect the evidence <span>↓</span></a></div><div className="statline"><span><b>8</b> researched models</span><span><b>24</b> cited proof points</span><span><b>5</b> industries</span><span className="method">No model is approved for autonomous high-stakes decisions</span></div><div className="orbit" aria-hidden="true"><div className="orb orb1">◎</div><div className="orb orb2">A</div><div className="orb orb3">✦</div><div className="orb orb4">∞</div><div className="orb center">?</div></div></section>

  <section id="advisor" className="advisor section-pad"><div className="section-head"><div><span className="kicker">01 / MODEL ADVISOR</span><h2>Tell us what<br/>you need to do.</h2></div><p>The advisor detects task, input type and deployment constraints. Its score combines task fit, matched signals and your priorities—then shows the evidence behind the recommendation.</p></div>
   <div className="advisor-shell"><div className="advisor-input"><label htmlFor="usecase">DESCRIBE THE WORK</label><textarea id="usecase" value={useText} onChange={e=>setUseText(e.target.value)} placeholder="Example: I need to compare architectural drawings against a 300-page specification, identify conflicts, and draft RFIs. The documents are confidential…"/><div className="charhint"><span>Be specific about inputs, output, privacy and budget.</span><b>{useText.length} chars</b></div><span className="mini-label">TRY AN EXAMPLE</span><div className="preset-row">{presets.map(p=><button key={p} onClick={()=>setUseText(p)}>{p}</button>)}</div></div>
    <div className="advisor-controls"><span className="mini-label">WHAT MATTERS MOST?</span><div className="priority-list">{priorityDefs.map(p=><button key={p.id} className={priorities.includes(p.id)?"active":""} onClick={()=>setPriorities(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}><i>{priorities.includes(p.id)?"✓":"+"}</i>{p.label}</button>)}</div><button className="analyze" disabled={useText.trim().length<8} onClick={runAdvisor}>Analyze my use case <span>→</span></button><p>Runs locally in your browser. Your description is not sent anywhere.</p></div></div>
   {results&&<div id="recommendation" className="recommendation"><div className="rec-head"><div><span>RECOMMENDATION</span><h3>{results[0].m.name}</h3><p>Best fit for your described <b>{domains.find(d=>d.id===results[0].inferred)?.name.toLowerCase()}</b> workflow.</p></div><div className="confidence"><b>{useText.length>55?"Strong signal":"Directional"}</b><span>recommendation confidence</span></div></div><div className="rec-body"><div className="rec-rank"><div className={`big-mark ${results[0].m.tone}`}>{results[0].m.mark}</div><b>{results[0].score}</b><span>FIT SCORE</span></div><div className="rec-why"><span>WHY IT RANKED FIRST</span><ul>{results[0].reasons.map(x=><li key={x}>{x}</li>)}</ul><div className="proof-strip">{results[0].m.proofs.slice(0,2).map(p=><a key={p.label} href={p.url} target="_blank" rel="noreferrer"><b>{p.value}</b><span>{p.label}</span><small>{p.source} ↗</small></a>)}</div></div><div className="rec-next"><span>RUNNERS-UP</span>{results.slice(1,3).map((r,i)=><button key={r.m.id} onClick={()=>{if(!selected.includes(r.m.id))toggleCompare(r.m.id);document.getElementById("compare")?.scrollIntoView({behavior:"smooth"})}}><b>0{i+2}</b><span>{r.m.name}<small>{r.score} fit · add to compare</small></span><em>+</em></button>)}</div></div><div className="rec-warning"><b>Important limitation</b><span>{caution[results[0].inferred as keyof typeof caution]}</span></div></div>}
  </section>

  <section id="finder" className="finder section-pad"><div className="section-head"><div><span className="kicker">02 / DOMAIN MAP</span><h2>Explore the work,<br/>not the hype.</h2></div><p>Browse common workflows by industry. Rankings are editorial task-fit estimates—not universal benchmark scores.</p></div><div className="domain-tabs" role="tablist">{domains.map(d=><button key={d.id} onClick={()=>setDomain(d.id)} className={domain===d.id?"active":""} role="tab" aria-selected={domain===d.id}><span>{d.icon}</span>{d.name}</button>)}</div><div className="recommend-grid"><div className="domain-card"><div className="domain-title"><span className="domain-icon">{current.icon}</span><div><span>EXPLORE THE DOMAIN</span><h3>{current.name}</h3><p>{current.desc}</p></div></div><div className="areas">{current.areas.map((a,i)=><button key={a}><span>0{i+1}</span>{a}<b>↗</b></button>)}</div><div className="example"><span>EXAMPLE WORKFLOW</span><p>“{current.example}”</p></div></div><div className="winner-card"><div className="winner-top"><span>BEST EDITORIAL FIT</span><span className="score">{ranked[0].scores[domain]} / 100</span></div><div className={`big-mark ${ranked[0].tone}`}>{ranked[0].mark}</div><p className="maker">{ranked[0].maker}</p><h3>{ranked[0].name}</h3><p className="bestfor">{ranked[0].best}</p><div className="why"><span>EVIDENCE SNAPSHOT</span><ul>{ranked[0].proofs.slice(0,2).map(p=><li key={p.label}><a href={p.url} target="_blank" rel="noreferrer">{p.label}: <b>{p.value}</b> · {p.source} ↗</a></li>)}</ul></div><a target="_blank" rel="noreferrer" href={ranked[0].link} className="access">Open official page <span>↗</span></a><p className="micro">Recommendation is not approval for autonomous use.</p></div></div><div className="caution"><span>!</span><div><b>{current.name} safety note</b><p>{caution[domain as keyof typeof caution]}</p></div></div></section>

  <section id="catalog" className="catalog section-pad"><div className="section-head dark"><div><span className="kicker">03 / EVIDENCE LIBRARY</span><h2>Claims you can<br/><em>open and inspect.</em></h2></div><p>Each proof links to a model card, technical report or official documentation. Provider benchmark results are labeled self-reported and may use different harnesses.</p></div><div className="catalog-tools"><label>⌕<input aria-label="Search models" placeholder="Search models or capabilities" value={query} onChange={e=>setQuery(e.target.value)}/></label><div>{["All","App + API","API","Open weights"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><div className="model-grid">{visible.map((m,i)=><article className="model-card" key={m.id}><div className="model-num">{String(i+1).padStart(2,"0")}<button className={selected.includes(m.id)?"checked":""} onClick={()=>toggleCompare(m.id)} aria-label={`Compare ${m.name}`}>{selected.includes(m.id)?"✓":"+"}</button></div><div className={`model-mark ${m.tone}`}>{m.mark}</div><span className="model-type">{m.type}</span><h3>{m.name}</h3><p className="by">by {m.maker}</p><div className="spec-row"><span><b>{m.context}</b> context</span><span><b>{m.price}</b> / 1M tokens</span></div><div className="tagrow">{m.tags.map(t=><span key={t}>{t}</span>)}</div><dl><div><dt>SHINES AT</dt><dd>{m.best}</dd></div><div><dt>WATCH FOR</dt><dd>{m.limits}</dd></div></dl><div className="card-proofs">{m.proofs.slice(0,2).map(p=><a key={p.label} href={p.url} target="_blank" rel="noreferrer"><b>{p.value}</b><span>{p.label}<small>{p.source} ↗</small></span></a>)}</div><div className="card-foot"><span className={m.access==="Open weights"?"open":""}>{m.access}</span><a href={m.link} target="_blank" rel="noreferrer">{m.access==="Open weights"?"Get weights":"Open"} ↗</a></div></article>)}</div><div className="methodology"><b>How to read the proof</b><p>Benchmark scores are not directly comparable unless the dataset, model version, prompting, tool access, reasoning effort and evaluation harness match. Treat them as evidence of a demonstrated capability—not a guarantee for your task.</p><a href={independent} target="_blank" rel="noreferrer">Cross-check independent model evaluations ↗</a></div></section>

  <section id="compare" className="compare section-pad"><div className="section-head"><div><span className="kicker">04 / EVIDENCE COMPARE</span><h2>Select models.<br/>Inspect the proof.</h2></div><p>Choose up to four. The comparison combines published specifications, editorial task fit and direct links to the underlying evidence.</p></div><div className="select-models"><span>SELECT MODELS ({selected.length}/4)</span><div>{models.map(m=><button key={m.id} className={selected.includes(m.id)?"active":""} onClick={()=>toggleCompare(m.id)}><i>{selected.includes(m.id)?"✓":"+"}</i>{m.name}</button>)}</div></div><div className="compare-wrap detailed"><div className="compare-labels"><b>MODEL</b><span>Context</span><span>Modalities</span><span>Access / license</span><span>{current.name} fit</span><span>Published proof</span><span>Official page</span></div>{selected.map(id=>{const m=models.find(x=>x.id===id)!;return <div className="compare-col" key={id}><div className="compare-model"><span className={`tiny-mark ${m.tone}`}>{m.mark}</span><b>{m.name}</b><button onClick={()=>toggleCompare(id)}>×</button></div><div className="compare-copy"><b>{m.context}</b><small>tokens</small></div><div className="compare-copy">{m.modalities}</div><div className="compare-copy"><b>{m.access}</b><small>{m.license}</small></div><div className="bar-cell"><span style={{width:`${m.scores[domain]}%`}}></span><b>{m.scores[domain]}</b></div><div className="compare-proof">{m.proofs.slice(0,2).map(p=><a href={p.url} target="_blank" rel="noreferrer" key={p.label}><b>{p.value}</b> {p.label} ↗</a>)}</div><div className="access-cell"><a href={m.link} target="_blank" rel="noreferrer">Open source ↗</a></div></div>})}{selected.length===0&&<div className="empty">Choose models above to compare.</div>}</div><p className="compare-note">Comparison domain: <b>{current.name}</b>. Change it in the Domain Map above. Fit scores are Model Atlas editorial estimates; published proof points retain their original source and methodology.</p></section>
  <footer><div className="brand"><span className="brand-mark">M</span><span>Model Atlas</span></div><p>Choose with evidence. Deploy with oversight.</p><div><a href="#top">Back to top ↑</a><span>Research checked · Aug 2026</span></div></footer>
 </main>
}
