"use client";

import { useMemo, useState } from "react";

type Proof = { label:string; value:string; note:string; url:string; source:string };
type Model = {
  id:string; name:string; maker:string; mark:string; tone:string; type:string;
  access:"API"|"Open weights"|"App + API"; best:string; limits:string; tags:string[];
  context:string; price:string; modalities:string; license:string; scores:Record<string,number>;
  keywords:string[]; link:string; proofs:Proof[];
};

const independent = "https://artificialanalysis.ai/models";
const models:Model[] = [
  {id:"gpt",name:"GPT-5.6 Sol",maker:"OpenAI",mark:"◎",tone:"lime",type:"Frontier reasoning",access:"App + API",context:"1.05M",price:"$5 / $30",modalities:"Text + image input",license:"Hosted",best:"Complex professional work, production coding, agents and computer use",limits:"Cloud-hosted; expensive output; no audio/video input; high-stakes facts still require verification.",tags:["Reasoning","Code","Vision","Tools"],scores:{medical:94,software:98,construction:94,creative:88,research:96},keywords:["code","software","agent","cyber","research","science","cad","construction","spreadsheet","computer use"],link:"https://developers.openai.com/api/docs/models/gpt-5.6-sol",proofs:[{label:"Professional workflows",value:"52.7%",note:"Agents’ Last Exam, max reasoning",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"Agentic browsing",value:"92.2%",note:"BrowseComp with Ultra",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"Published context",value:"1.05M",note:"128K maximum output",url:"https://developers.openai.com/api/docs/models/gpt-5.6-sol",source:"OpenAI API docs"}]},
  {id:"claude",name:"Claude Opus 4.8",maker:"Anthropic",mark:"A",tone:"coral",type:"Frontier reasoning",access:"App + API",context:"200K",price:"$5 / $25",modalities:"Text + image input",license:"Hosted",best:"Large codebases, long-form analysis, careful writing and document-heavy work",limits:"Cloud-hosted; premium price; usage limits and effort settings change latency and cost.",tags:["Reasoning","Code","Documents","Tools"],scores:{medical:92,software:97,construction:89,creative:96,research:95},keywords:["write","writing","legal","document","codebase","migration","analysis","financial","style","review"],link:"https://www.anthropic.com/news/claude-opus-4-8",proofs:[{label:"Coding",value:"88.6%",note:"SWE-bench Verified",url:"https://www.anthropic.com/system-cards",source:"Anthropic system card"},{label:"Browser use",value:"84.3%",note:"BrowseComp, single agent",url:"https://www.anthropic.com/system-cards",source:"Anthropic system card"},{label:"Self-critique",value:"4×",note:"Less likely than 4.7 to miss flaws in its code",url:"https://www.anthropic.com/news/claude-opus-4-8",source:"Anthropic · self-reported"}]},
  {id:"gemini",name:"Gemini 3.1 Pro",maker:"Google",mark:"✦",tone:"blue",type:"Multimodal frontier",access:"App + API",context:"1M",price:"See current rate card",modalities:"Text, image, audio + video",license:"Hosted",best:"Multimodal research, very long contexts, video/audio and Google workflows",limits:"Preview/stable variants change; 1M-context retrieval is materially weaker than at 128K in Google’s own MRCR result.",tags:["Vision","Video","Long context","Tools"],scores:{medical:95,software:94,construction:97,creative:91,research:98},keywords:["video","audio","image","diagram","drawing","blueprint","long document","google","multimodal","lecture"],link:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",proofs:[{label:"Science knowledge",value:"94.3%",note:"GPQA Diamond, no tools",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"},{label:"Abstract reasoning",value:"77.1%",note:"ARC-AGI-2 verified",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"},{label:"Multimodal",value:"80.5%",note:"MMMU-Pro, no tools",url:"https://deepmind.google/models/model-cards/gemini-3-1-pro/",source:"Google model card"}]},
  {id:"llama",name:"Llama 4 Maverick",maker:"Meta",mark:"∞",tone:"violet",type:"Open-weight multimodal",access:"Open weights",context:"1M",price:"Infrastructure cost",modalities:"Text + image input",license:"Llama license",best:"Private deployments, customization and high-throughput multimodal applications",limits:"400B total parameters; self-hosting needs serious hardware, evaluation, security and safety engineering.",tags:["Open weights","Vision","Fine-tune"],scores:{medical:78,software:87,construction:85,creative:86,research:82},keywords:["private","on premise","self host","fine tune","customize","image","high volume"],link:"https://ai.meta.com/llama/get-started/",proofs:[{label:"Architecture",value:"17B active",note:"128 experts; 400B total parameters",url:"https://ai.meta.com/blog/llama-4-multimodal-intelligence/",source:"Meta release"},{label:"Availability",value:"Weights",note:"Direct and partner downloads",url:"https://ai.meta.com/llama/get-started/",source:"Meta documentation"},{label:"Input",value:"Multimodal",note:"Native text and image understanding",url:"https://ai.meta.com/blog/llama-4-multimodal-intelligence/",source:"Meta release"}]},
  {id:"deepseek",name:"DeepSeek R1",maker:"DeepSeek",mark:"D",tone:"blue",type:"Open reasoning",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text",license:"MIT (base R1)",best:"Math, reasoning research and cost-controlled open deployment",limits:"Older than today’s frontier; large local inference footprint; cited results use the authors’ own evaluation settings.",tags:["Reasoning","Math","Open weights"],scores:{medical:76,software:91,construction:79,creative:70,research:88},keywords:["math","equation","reasoning","open source","self host","research","codeforces"],link:"https://github.com/deepseek-ai/DeepSeek-R1",proofs:[{label:"Mathematics",value:"97.3%",note:"MATH-500 pass@1",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek technical report"},{label:"Coding",value:"65.9%",note:"LiveCodeBench pass@1-CoT",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek technical report"},{label:"License",value:"MIT",note:"Base R1; distilled models inherit base-model terms",url:"https://github.com/deepseek-ai/DeepSeek-R1",source:"DeepSeek repository"}]},
  {id:"mistral",name:"Mistral Medium 3.5",maker:"Mistral AI",mark:"M",tone:"coral",type:"Open multimodal agent",access:"Open weights",context:"256K",price:"$1.50 / $7.50",modalities:"Text + image / OCR",license:"Modified MIT",best:"Multilingual enterprise agents, coding, OCR and European deployment",limits:"Modified license needs review; ecosystem and independent evaluation coverage are smaller than for the largest labs.",tags:["Multilingual","Code","Open weights"],scores:{medical:82,software:92,construction:92,creative:86,research:86},keywords:["europe","european","multilingual","french","german","spanish","italian","ocr","document","private"],link:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",proofs:[{label:"Published context",value:"256K",note:"Frontier-class multimodal model",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral model card"},{label:"API price / 1M",value:"$1.50 / $7.50",note:"Input / output at publication",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral documentation"},{label:"Distribution",value:"Open weights",note:"Modified MIT license",url:"https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",source:"Mistral model card"}]},
  {id:"qwen",name:"Qwen 3.6 35B-A3B",maker:"Alibaba Qwen",mark:"Q",tone:"violet",type:"Efficient open agent",access:"Open weights",context:"256K",price:"Infrastructure cost",modalities:"Text + image",license:"See model license",best:"Efficient agentic coding, multilingual and Chinese-language applications",limits:"Provider benchmarks include internal tests; licensing, regional compliance and deployment controls need review.",tags:["Open weights","Multilingual","Code"],scores:{medical:79,software:93,construction:84,creative:81,research:87},keywords:["chinese","multilingual","coding","efficient","small gpu","open source","agent","self host"],link:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",proofs:[{label:"Efficiency",value:"3B active",note:"35B total MoE parameters",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"},{label:"Context",value:"256K",note:"Published evaluation setting",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"},{label:"Availability",value:"Weights + API",note:"Hugging Face, ModelScope and Qwen Studio",url:"https://qwen.ai/blog?id=qwen3.6-35b-a3b",source:"Qwen release"}]},
  {id:"gemma",name:"Gemma 4 31B",maker:"Google",mark:"G",tone:"lime",type:"Efficient open multimodal",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text + image",license:"Gemma terms",best:"Private multimodal apps, research, tuning and consumer-workstation deployment",limits:"Smaller than frontier hosted models; Google warns of factual errors, bias and weak common-sense reasoning.",tags:["Open weights","Efficient","Fine-tune"],scores:{medical:84,software:90,construction:87,creative:84,research:85},keywords:["local","workstation","fine tune","open model","privacy","image","medical image","efficient"],link:"https://ai.google.dev/gemma/docs/core/model_card_4",proofs:[{label:"Knowledge",value:"85.2%",note:"MMLU-Pro, 31B instruction model",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"},{label:"Coding",value:"80.0%",note:"LiveCodeBench v6",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"},{label:"Medical multimodal",value:"61.3%",note:"MedXPertQA-MM",url:"https://ai.google.dev/gemma/docs/core/model_card_4",source:"Google model card"}]},
  {id:"gpt-terra",name:"GPT-5.6 Terra",maker:"OpenAI",mark:"◎",tone:"lime",type:"Balanced reasoning",access:"API",context:"1.05M",price:"$2.50 / $15",modalities:"Text + image input",license:"Hosted",best:"Everyday production agents that need strong reasoning at lower cost than Sol",limits:"Cloud-only; high-context requests cost more; still needs workload-specific evaluation.",tags:["Reasoning","Code","Tools","Balanced"],scores:{medical:91,software:95,construction:92,creative:87,research:93},keywords:["balanced","production","agent","code","cost","volume","automation"],link:"https://developers.openai.com/api/docs/models",proofs:[{label:"Professional workflows",value:"50.4%",note:"Agents’ Last Exam",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"Published context",value:"1.05M",note:"128K maximum output",url:"https://developers.openai.com/api/docs/models",source:"OpenAI API docs"}]},
  {id:"gpt-luna",name:"GPT-5.6 Luna",maker:"OpenAI",mark:"◎",tone:"lime",type:"Economical reasoning",access:"API",context:"1.05M",price:"$1 / $6",modalities:"Text + image input",license:"Hosted",best:"High-volume classification, extraction, subagents and cost-sensitive automation",limits:"Less capable than Sol on the hardest work; output price can still dominate long generations.",tags:["Efficient","Code","Tools","High volume"],scores:{medical:87,software:92,construction:89,creative:84,research:89},keywords:["cheap","cost","volume","classify","extract","subagent","fast"],link:"https://developers.openai.com/api/docs/models/gpt-5.6-luna",proofs:[{label:"Professional workflows",value:"50.3%",note:"Agents’ Last Exam",url:"https://openai.com/index/gpt-5-6/",source:"OpenAI · self-reported"},{label:"API price / 1M",value:"$1 / $6",note:"Input / output",url:"https://developers.openai.com/api/docs/models/gpt-5.6-luna",source:"OpenAI API docs"}]},
  {id:"fable",name:"Claude Fable 5",maker:"Anthropic",mark:"A",tone:"coral",type:"Safeguarded frontier",access:"App + API",context:"200K",price:"$10 / $50",modalities:"Text + image input",license:"Hosted",best:"The most difficult coding, research, knowledge-work and vision tasks",limits:"Very expensive; conservative safeguards can route some requests to Opus 4.8; not an autonomous authority.",tags:["Frontier","Reasoning","Code","Vision"],scores:{medical:96,software:99,construction:93,creative:97,research:99},keywords:["hardest","complex","frontier","science","research","code","vision","professional"],link:"https://www.anthropic.com/news/claude-fable-5-mythos-5",proofs:[{label:"General availability",value:"Fable 5",note:"Safeguarded Mythos-class model",url:"https://www.anthropic.com/news/claude-fable-5-mythos-5",source:"Anthropic release"},{label:"API price / 1M",value:"$10 / $50",note:"Input / output",url:"https://www.anthropic.com/news/claude-fable-5-mythos-5",source:"Anthropic release"}]},
  {id:"sonnet",name:"Claude Sonnet 5",maker:"Anthropic",mark:"A",tone:"coral",type:"Scaled frontier",access:"App + API",context:"200K",price:"$2 / $10*",modalities:"Text + image input",license:"Hosted",best:"Coding, agents and professional work at production scale",limits:"Introductory pricing ends Aug 31, 2026; hosted only; complex work may still favor Fable or Opus.",tags:["Code","Agents","Documents","Balanced"],scores:{medical:91,software:97,construction:91,creative:94,research:94},keywords:["code","agent","professional","scale","document","balanced","production"],link:"https://www.anthropic.com/news/claude-sonnet-5",proofs:[{label:"Launch focus",value:"Coding + agents",note:"Frontier performance at scale",url:"https://www.anthropic.com/news/claude-sonnet-5",source:"Anthropic release"},{label:"Intro price / 1M",value:"$2 / $10",note:"Through Aug 31, 2026",url:"https://www.anthropic.com/news/claude-sonnet-5",source:"Anthropic release"}]},
  {id:"gemini-flash",name:"Gemini 3.6 Flash",maker:"Google",mark:"✦",tone:"blue",type:"Fast multimodal agent",access:"API",context:"1M",price:"See rate card",modalities:"Text, image, audio + video",license:"Hosted",best:"Fast multimodal automation, coding loops and high-volume subagents",limits:"Flash prioritizes speed and efficiency over peak Pro capability; availability and rate cards change.",tags:["Fast","Vision","Video","Tools"],scores:{medical:89,software:94,construction:94,creative:89,research:92},keywords:["fast","video","audio","image","agent","high volume","google","multimodal"],link:"https://ai.google.dev/gemini-api/docs/changelog",proofs:[{label:"Availability",value:"GA",note:"Stable release July 2026",url:"https://ai.google.dev/gemini-api/docs/changelog",source:"Google API changelog"},{label:"Input limit",value:"1M",note:"Flash family multimodal context",url:"https://ai.google.dev/gemini-api/docs/models",source:"Google API docs"}]},
  {id:"grok",name:"Grok 4.20",maker:"xAI",mark:"X",tone:"violet",type:"Fast agentic model",access:"App + API",context:"2M",price:"See rate card",modalities:"Text + image input",license:"Hosted",best:"Fast agents, tool calling, current-events workflows and X-native research",limits:"Hosted only; social-web grounding can amplify noisy or low-quality sources; verify citations.",tags:["Agents","Search","Tools","Fast"],scores:{medical:86,software:94,construction:87,creative:89,research:92},keywords:["x","twitter","social","current events","search","agent","fast","tool"],link:"https://docs.x.ai/developers/models/grok-4.20",proofs:[{label:"Model focus",value:"Agentic",note:"High speed and tool calling",url:"https://docs.x.ai/developers/models/grok-4.20",source:"xAI documentation"},{label:"Safety record",value:"System card",note:"Published April 2026",url:"https://data.x.ai/2026-04-07-grok-4-20-model-card.pdf",source:"xAI system card"}]},
  {id:"deepseek-v4",name:"DeepSeek V4 Pro",maker:"DeepSeek",mark:"D",tone:"blue",type:"Low-cost frontier API",access:"API",context:"1M",price:"$0.435 / $0.87",modalities:"Text",license:"Hosted API",best:"Extremely low-cost reasoning, coding, long contexts and high-volume tool use",limits:"Regional governance and data-handling need review; official pricing can change; text-only input.",tags:["Reasoning","Code","Long context","Low cost"],scores:{medical:87,software:96,construction:86,creative:80,research:94},keywords:["cheap","low cost","code","reasoning","long context","math","api"],link:"https://api-docs.deepseek.com/quick_start/pricing/",proofs:[{label:"Published context",value:"1M",note:"384K maximum output",url:"https://api-docs.deepseek.com/quick_start/pricing/",source:"DeepSeek API docs"},{label:"API price / 1M",value:"$0.435 / $0.87",note:"Cache-miss input / output",url:"https://api-docs.deepseek.com/quick_start/pricing/",source:"DeepSeek API docs"}]},
  {id:"glm",name:"GLM-5.2",maker:"Z.ai",mark:"Z",tone:"lime",type:"Open long-horizon model",access:"Open weights",context:"1M",price:"Infrastructure cost",modalities:"Text",license:"MIT",best:"Very long coding-agent trajectories, research and sovereign open deployment",limits:"Massive serving footprint; provider comparisons use specific harnesses and judging models.",tags:["Open weights","Code","Long context","Agents"],scores:{medical:84,software:97,construction:87,creative:80,research:95},keywords:["long horizon","code","agent","open source","mit","research","1m","sovereign"],link:"https://z.ai/blog/glm-5.2",proofs:[{label:"Terminal work",value:"81.0",note:"Terminal-Bench 2.1",url:"https://z.ai/blog/glm-5.2",source:"Z.ai · self-reported"},{label:"Published context",value:"1M",note:"MIT open-source weights",url:"https://z.ai/blog/glm-5.2",source:"Z.ai release"}]},
  {id:"minimax",name:"MiniMax M3",maker:"MiniMax",mark:"M3",tone:"coral",type:"Open multimodal frontier",access:"Open weights",context:"1M",price:"Infrastructure cost",modalities:"Text, image + video",license:"See model license",best:"Open multimodal agents, coding, office workflows and computer use",limits:"Very new; independent evidence is limited; large-scale self-hosting remains complex.",tags:["Open weights","Vision","Video","Agents"],scores:{medical:84,software:95,construction:92,creative:91,research:91},keywords:["video","image","computer use","open source","coding","office","agent","1m"],link:"https://www.minimax.io/blog/minimax-m3",proofs:[{label:"Published context",value:"1M",note:"Native multimodality",url:"https://www.minimax.io/blog/minimax-m3",source:"MiniMax release"},{label:"Input",value:"Image + video",note:"Also supports computer use",url:"https://www.minimax.io/blog/minimax-m3",source:"MiniMax release"}]},
  {id:"command",name:"Command A+",maker:"Cohere",mark:"C",tone:"blue",type:"Sovereign enterprise agent",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text + image + tools",license:"Apache 2.0",best:"Air-gapped enterprise RAG, multilingual agents and regulated infrastructure",limits:"218B total parameters; minimum practical hardware is substantial; benchmark results are provider-reported.",tags:["Open weights","RAG","Multilingual","Agents"],scores:{medical:88,software:91,construction:90,creative:84,research:91},keywords:["rag","citation","sovereign","air gap","government","regulated","multilingual","enterprise"],link:"https://cohere.com/blog/command-a-plus",proofs:[{label:"Languages",value:"48",note:"Multilingual support",url:"https://cohere.com/blog/command-a-plus",source:"Cohere release"},{label:"Architecture",value:"25B active",note:"218B total; Apache 2.0",url:"https://cohere.com/blog/command-a-plus",source:"Cohere release"}]},
  {id:"granite",name:"Granite 4.0 H Small",maker:"IBM",mark:"I",tone:"violet",type:"Efficient enterprise open",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text",license:"Apache 2.0",best:"Enterprise RAG, agents, function calling and memory-efficient private deployment",limits:"Not a frontier reasoning model; hybrid architecture support varies across inference runtimes.",tags:["Open weights","RAG","Efficient","Enterprise"],scores:{medical:80,software:87,construction:83,creative:75,research:84},keywords:["ibm","enterprise","rag","function calling","efficient","private","iso","edge"],link:"https://www.ibm.com/granite/docs/models/granite",proofs:[{label:"Memory",value:"70% lower",note:"Than similar models, per IBM",url:"https://www.ibm.com/granite/docs/models/granite",source:"IBM documentation"},{label:"Architecture",value:"32B / 9B",note:"Total / activated parameters",url:"https://www.ibm.com/granite/docs/models/granite",source:"IBM documentation"}]},
  {id:"phi",name:"Phi-4 Multimodal",maker:"Microsoft",mark:"P",tone:"lime",type:"Small on-device model",access:"Open weights",context:"128K",price:"Infrastructure cost",modalities:"Text, image + audio",license:"MIT",best:"On-device and edge multimodal applications with limited hardware",limits:"A 5.6B small model cannot match frontier models on the hardest reasoning or agentic tasks.",tags:["Open weights","On-device","Audio","Vision"],scores:{medical:77,software:83,construction:82,creative:80,research:79},keywords:["edge","device","small","mobile","audio","speech","vision","offline"],link:"https://azure.microsoft.com/en-us/blog/empowering-innovation-the-next-generation-of-the-phi-family/",proofs:[{label:"Model size",value:"5.6B",note:"Unified speech, vision and text",url:"https://azure.microsoft.com/en-us/blog/empowering-innovation-the-next-generation-of-the-phi-family/",source:"Microsoft release"},{label:"Deployment",value:"Edge",note:"Designed for low-latency local use",url:"https://azure.microsoft.com/en-us/products/phi/",source:"Microsoft documentation"}]},
  {id:"nova",name:"Amazon Nova Premier",maker:"AWS",mark:"N",tone:"coral",type:"Bedrock multimodal teacher",access:"API",context:"1M",price:"See Bedrock pricing",modalities:"Text, image + video",license:"Hosted",best:"AWS-native complex workflows, multimodal documents and model distillation",limits:"AWS marks this version legacy with EOL September 14, 2026; plan migration before new production adoption.",tags:["AWS","Vision","Video","Agents"],scores:{medical:84,software:88,construction:91,creative:86,research:89},keywords:["aws","bedrock","distill","video","image","document","agent","enterprise"],link:"https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",proofs:[{label:"Published context",value:"1M",note:"25K maximum output",url:"https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",source:"AWS documentation"},{label:"Lifecycle",value:"Legacy",note:"EOL Sep 14, 2026",url:"https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",source:"AWS documentation"}]},
  {id:"sonar",name:"Sonar Pro",maker:"Perplexity",mark:"S",tone:"blue",type:"Search-grounded model",access:"API",context:"200K",price:"$3 / $15 + search",modalities:"Text + web search",license:"Hosted",best:"Current, citation-heavy research and complex multi-step web questions",limits:"Non-reasoning model; answer quality depends on retrieved sources; search requests add cost.",tags:["Search","Citations","Research","RAG"],scores:{medical:88,software:86,construction:84,creative:82,research:96},keywords:["latest","current","web","source","citation","search","news","research"],link:"https://docs.perplexity.ai/docs/sonar/models/sonar-pro",proofs:[{label:"Search depth",value:"2×",note:"More results than standard Sonar",url:"https://docs.perplexity.ai/docs/sonar/models/sonar-pro",source:"Perplexity documentation"},{label:"Published context",value:"200K",note:"Complex multi-step Q&A",url:"https://docs.perplexity.ai/docs/sonar/models/sonar-pro",source:"Perplexity documentation"}]},
  {id:"nemotron",name:"Nemotron 3 Ultra",maker:"NVIDIA",mark:"N",tone:"violet",type:"Open enterprise reasoning",access:"Open weights",context:"1M",price:"Infrastructure cost",modalities:"Text",license:"NVIDIA Open Model",best:"Open enterprise agents, reasoning and long-context GPU-optimized deployment",limits:"Large 550B-total MoE model; infrastructure-intensive; use-case fit must be evaluated on your own stack.",tags:["Open weights","Agents","Long context","Enterprise"],scores:{medical:83,software:92,construction:84,creative:78,research:92},keywords:["nvidia","gpu","enterprise","open source","long context","agent","reasoning"],link:"https://research.nvidia.com/labs/nemotron/",proofs:[{label:"Architecture",value:"550B / 55B",note:"Total / active parameters",url:"https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf",source:"NVIDIA report"},{label:"Long context",value:"1M",note:"94.7 RULER in provider report",url:"https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf",source:"NVIDIA · self-reported"}]},
];

const domains=[
 {id:"medical",icon:"✚",name:"Medical & Health",desc:"Clinical support, research, operations",areas:["Clinical decision support","Medical imaging review","Patient education","Literature synthesis"],example:"Summarize a longitudinal record and flag missing evidence—always reviewed by a licensed clinician."},
 {id:"software",icon:"⌘",name:"Technology",desc:"Engineering, data, cybersecurity",areas:["Software engineering","Data analysis","Security review","Product research"],example:"Trace a failing integration test across a repository and propose a minimal, testable patch."},
 {id:"construction",icon:"▰",name:"Construction",desc:"Planning, design, field operations",areas:["Drawing & image review","Bid document analysis","Safety planning","Schedule risk"],example:"Compare plan sheets with a specification package and draft an RFI for inconsistencies."},
 {id:"creative",icon:"✦",name:"Creative Work",desc:"Writing, design, media",areas:["Campaign concepts","Editorial writing","Visual ideation","Video pre-production"],example:"Turn a product brief into three campaign territories with channel-ready copy."},
 {id:"research",icon:"◫",name:"Research & Education",desc:"Discovery, synthesis, tutoring",areas:["Evidence synthesis","Data interpretation","Adaptive tutoring","Grant research"],example:"Build a sourced evidence map that separates findings, uncertainty and open questions."},
 {id:"finance",icon:"$",name:"Finance & Banking",desc:"Analysis, risk, operations",areas:["Financial document analysis","Fraud & anomaly review","Investment research","Regulatory reporting"],example:"Compare quarterly filings, trace every claim to a source, and produce a risk memo for analyst review."},
 {id:"legal",icon:"§",name:"Legal Services",desc:"Discovery, contracts, research",areas:["Contract review","Legal research","E-discovery triage","Compliance mapping"],example:"Extract obligations from a contract set and create a clause-by-clause review table with citations."},
 {id:"marketing",icon:"◆",name:"Marketing & Sales",desc:"Campaigns, content, intelligence",areas:["Campaign strategy","Customer research","Sales enablement","Content operations"],example:"Synthesize interview transcripts into audience segments and draft evidence-based campaign territories."},
 {id:"manufacturing",icon:"⚙",name:"Manufacturing",desc:"Quality, maintenance, supply chain",areas:["Visual quality inspection","Maintenance support","Process documentation","Supply-chain risk"],example:"Analyze equipment manuals and inspection images to draft a technician checklist for expert approval."},
 {id:"retail",icon:"◇",name:"Retail & Commerce",desc:"Catalogs, service, forecasting",areas:["Catalog enrichment","Customer support","Demand analysis","Merchandising"],example:"Classify and enrich 50,000 product records while flagging low-confidence attributes for review."},
 {id:"energy",icon:"⌁",name:"Energy & Utilities",desc:"Assets, compliance, operations",areas:["Asset documentation","Grid & demand analysis","Field-service support","Regulatory research"],example:"Synthesize inspection records and sensor summaries into a prioritized maintenance briefing."},
 {id:"agriculture",icon:"♧",name:"Agriculture",desc:"Crop, equipment, supply",areas:["Crop image analysis","Agronomy research","Equipment support","Supply forecasting"],example:"Analyze crop images and field notes to highlight anomalies for an agronomist—not diagnose autonomously."},
 {id:"government",icon:"▥",name:"Government & Public",desc:"Services, policy, sovereignty",areas:["Policy analysis","Citizen services","Records processing","Sovereign deployment"],example:"Summarize public consultation submissions with traceable themes, dissenting views and source references."},
 {id:"operations",icon:"↻",name:"Business Operations",desc:"Workflow, service, knowledge",areas:["Process automation","Knowledge management","Customer operations","Document processing"],example:"Turn a complex operating procedure into a supervised workflow with approvals and exception handling."},
 {id:"hr",icon:"◉",name:"People & HR",desc:"Learning, talent, policy",areas:["Learning content","Policy Q&A","Workforce analysis","Recruiting support"],example:"Draft a skills-gap analysis from anonymized role data without making employment decisions."},
];
const caution={medical:"Not a medical device or clinician. Use approved, privacy-safe systems; require expert review and source verification.",software:"Generated code can be insecure or subtly wrong. Run tests, scans and human review before deployment.",construction:"Never use unverified output as stamped design, code compliance or site-safety instruction.",creative:"Check originality, rights, brand voice and factual claims before publishing.",research:"Models can fabricate citations and flatten disagreement. Open every source and inspect the underlying evidence.",finance:"Not financial advice. Require qualified review, source verification, audit trails and applicable controls.",legal:"Not legal advice. Privilege, confidentiality, jurisdiction and attorney review must be handled explicitly.",marketing:"Review claims, rights, bias, brand safety and disclosure requirements before publication.",manufacturing:"Do not use model output as an unsupervised safety, maintenance or quality-control decision.",retail:"Test for product-data errors, unfair personalization and privacy issues before customer-facing use.",energy:"Do not connect unvalidated model output directly to critical infrastructure or operational controls.",agriculture:"Image patterns are not a diagnosis. An agronomist should validate recommendations against field conditions.",government:"Public-sector deployments require accessibility, records, privacy, procurement and due-process review.",operations:"Keep approvals and deterministic controls around payments, account changes and other consequential actions.",hr:"Never allow a model to make autonomous hiring, promotion, discipline or termination decisions."};
const presets=["Review 300 pages of construction drawings and draft RFIs","Help a clinician summarize research on a rare disease","Refactor a TypeScript codebase with tests","Analyze interview videos and create a research brief"];
const priorityDefs=[{id:"privacy",label:"Private / self-hosted"},{id:"vision",label:"Images or video"},{id:"long",label:"Long documents"},{id:"cost",label:"Lower cost"},{id:"multilingual",label:"Multilingual"}];

const domainLeaders:Record<string,string[]>={finance:["fable","gpt","claude","grok","sonar"],legal:["fable","claude","sonnet","gpt"],marketing:["fable","claude","gemini","sonnet"],manufacturing:["gemini","minimax","nova","gpt"],retail:["gemini-flash","gpt-luna","sonnet","command"],energy:["gpt","gemini","fable","glm"],agriculture:["gemini","gemini-flash","minimax","gemma"],government:["command","granite","glm","mistral"],operations:["gpt","sonnet","fable","gemini-flash"],hr:["claude","sonnet","command","mistral"]};
function scoreFor(m:Model,domainId:string){
 const explicit=m.scores[domainId]; if(typeof explicit==="number")return explicit;
 const base=m.tags.includes("Frontier")||m.type.toLowerCase().includes("frontier")?89:m.access==="Open weights"?81:85;
 const leaders=domainLeaders[domainId]||[]; const rank=leaders.indexOf(m.id); const leaderBoost=rank>=0?8-rank:0;
 const signals:Record<string,string[]>={finance:["financial","reasoning","document","search"],legal:["legal","document","citation","long context"],marketing:["creative","vision","video","writing"],manufacturing:["vision","agent","enterprise","construction"],retail:["fast","high volume","multilingual","tools"],energy:["research","long context","construction","science"],agriculture:["vision","video","multilingual","research"],government:["sovereign","open weights","enterprise","multilingual"],operations:["agents","tools","document","enterprise"],hr:["document","multilingual","balanced","enterprise"]};
 const hay=`${m.tags.join(" ")} ${m.best} ${m.keywords.join(" ")}`.toLowerCase(); const signalBoost=(signals[domainId]||[]).filter(s=>hay.includes(s)).length*1.5;
 return Math.min(97,Math.round(base+leaderBoost+signalBoost));
}

function getRecommendations(text:string, priorities:string[]){
 const q=text.toLowerCase();
 const inferred = q.match(/medical|patient|clinical|disease|health|diagnos/) ? "medical" : q.match(/construct|drawing|blueprint|rfi|architect|site|building/) ? "construction" : q.match(/bank|finance|investment|fraud|portfolio|filing/) ? "finance" : q.match(/legal|law|contract|clause|discovery|compliance/) ? "legal" : q.match(/manufactur|factory|maintenance|quality inspection|supply chain/) ? "manufacturing" : q.match(/retail|catalog|product record|merchand|ecommerce/) ? "retail" : q.match(/energy|utility|grid|power plant|renewable/) ? "energy" : q.match(/crop|farm|agri|soil|livestock/) ? "agriculture" : q.match(/government|public sector|policy|citizen|sovereign/) ? "government" : q.match(/human resources|hiring|employee|workforce|recruit/) ? "hr" : q.match(/workflow|operations|process|customer service/) ? "operations" : q.match(/code|software|debug|typescript|python|api|cyber/) ? "software" : q.match(/campaign|marketing|sales|brand|content/) ? "marketing" : q.match(/write|creative|video|story|design/) ? "creative" : "research";
 return models.map(m=>{
   let score=scoreFor(m,inferred)*.55+25;
   const hits=m.keywords.filter(k=>q.includes(k)); score+=Math.min(hits.length*5,15);
   if(priorities.includes("privacy")) score+=m.access==="Open weights"?18:-9;
   if(priorities.includes("vision")) score+=/image|video/.test(m.modalities.toLowerCase())?11:-7;
   if(priorities.includes("long")) score+=parseFloat(m.context)>=256?9:0;
   if(priorities.includes("cost")) score+=m.access==="Open weights"?8:m.id==="mistral"?9:-3;
   if(priorities.includes("multilingual")) score+=m.tags.includes("Multilingual")?12:m.id==="gemini"?7:0;
   const reasons=[`${scoreFor(m,inferred)}/100 editorial fit for ${domains.find(d=>d.id===inferred)?.name}`,hits.length?`Matched: ${hits.slice(0,3).join(", ")}`:m.best,priorities.includes("privacy")&&m.access==="Open weights"?"Can be self-hosted for greater data control":""].filter(Boolean);
   return {m,score:Math.min(99,Math.round(score)),reasons,inferred};
 }).sort((a,b)=>b.score-a.score);
}

export default function Home(){
 const [domain,setDomain]=useState("medical"); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All");
 const [selected,setSelected]=useState<string[]>(["gpt","claude","gemini"]); const [useText,setUseText]=useState("");
 const [priorities,setPriorities]=useState<string[]>([]); const [results,setResults]=useState<ReturnType<typeof getRecommendations>|null>(null);
 const current=domains.find(d=>d.id===domain)!; const ranked=useMemo(()=>[...models].sort((a,b)=>scoreFor(b,domain)-scoreFor(a,domain)),[domain]);
 const visible=ranked.filter(m=>(filter==="All"||m.access===filter)&&`${m.name} ${m.maker} ${m.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
 const toggleCompare=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<4?[...s,id]:s);
 const runAdvisor=()=>{if(useText.trim().length<8)return;setResults(getRecommendations(useText,priorities));setTimeout(()=>document.getElementById("recommendation")?.scrollIntoView({behavior:"smooth",block:"center"}),50)};
 return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">M</span><span>Model Atlas</span></a><div className="navlinks"><a href="#advisor">Advisor</a><a href="#catalog">Evidence</a><a href="#compare">Compare</a></div><a className="nav-cta" href="#advisor">Describe your use <span>↘</span></a></nav>
  <section id="top" className="hero"><div className="eyebrow"><span>●</span> Evidence-led AI field guide · Research checked Aug 2026</div><h1>The right model<br/>for the <em>real work.</em></h1><p className="lede">Describe the job in plain language. Get a transparent recommendation, inspect the evidence, and compare the tradeoffs before you commit.</p><div className="hero-actions"><a href="#advisor" className="primary">Ask the model advisor <span>→</span></a><a href="#catalog" className="text-link">Inspect the evidence <span>↓</span></a></div><div className="statline"><span><b>{models.length}</b> researched models</span><span><b>{models.reduce((n,m)=>n+m.proofs.length,0)}</b> cited proof points</span><span><b>{domains.length}</b> industries</span><span className="method">No model is approved for autonomous high-stakes decisions</span></div><div className="orbit" aria-hidden="true"><div className="orb orb1">◎</div><div className="orb orb2">A</div><div className="orb orb3">✦</div><div className="orb orb4">∞</div><div className="orb center">?</div></div></section>

  <section id="advisor" className="advisor section-pad"><div className="section-head"><div><span className="kicker">01 / MODEL ADVISOR</span><h2>Tell us what<br/>you need to do.</h2></div><p>The advisor detects task, input type and deployment constraints. Its score combines task fit, matched signals and your priorities—then shows the evidence behind the recommendation.</p></div>
   <div className="advisor-shell"><div className="advisor-input"><label htmlFor="usecase">DESCRIBE THE WORK</label><textarea id="usecase" value={useText} onChange={e=>setUseText(e.target.value)} placeholder="Example: I need to compare architectural drawings against a 300-page specification, identify conflicts, and draft RFIs. The documents are confidential…"/><div className="charhint"><span>Be specific about inputs, output, privacy and budget.</span><b>{useText.length} chars</b></div><span className="mini-label">TRY AN EXAMPLE</span><div className="preset-row">{presets.map(p=><button key={p} onClick={()=>setUseText(p)}>{p}</button>)}</div></div>
    <div className="advisor-controls"><span className="mini-label">WHAT MATTERS MOST?</span><div className="priority-list">{priorityDefs.map(p=><button key={p.id} className={priorities.includes(p.id)?"active":""} onClick={()=>setPriorities(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}><i>{priorities.includes(p.id)?"✓":"+"}</i>{p.label}</button>)}</div><button className="analyze" disabled={useText.trim().length<8} onClick={runAdvisor}>Analyze my use case <span>→</span></button><p>Runs locally in your browser. Your description is not sent anywhere.</p></div></div>
   {results&&<div id="recommendation" className="recommendation"><div className="rec-head"><div><span>RECOMMENDATION</span><h3>{results[0].m.name}</h3><p>Best fit for your described <b>{domains.find(d=>d.id===results[0].inferred)?.name.toLowerCase()}</b> workflow.</p></div><div className="confidence"><b>{useText.length>55?"Strong signal":"Directional"}</b><span>recommendation confidence</span></div></div><div className="rec-body"><div className="rec-rank"><div className={`big-mark ${results[0].m.tone}`}>{results[0].m.mark}</div><b>{results[0].score}</b><span>FIT SCORE</span></div><div className="rec-why"><span>WHY IT RANKED FIRST</span><ul>{results[0].reasons.map(x=><li key={x}>{x}</li>)}</ul><div className="proof-strip">{results[0].m.proofs.slice(0,2).map(p=><a key={p.label} href={p.url} target="_blank" rel="noreferrer"><b>{p.value}</b><span>{p.label}</span><small>{p.source} ↗</small></a>)}</div></div><div className="rec-next"><span>RUNNERS-UP</span>{results.slice(1,3).map((r,i)=><button key={r.m.id} onClick={()=>{if(!selected.includes(r.m.id))toggleCompare(r.m.id);document.getElementById("compare")?.scrollIntoView({behavior:"smooth"})}}><b>0{i+2}</b><span>{r.m.name}<small>{r.score} fit · add to compare</small></span><em>+</em></button>)}</div></div><div className="rec-warning"><b>Important limitation</b><span>{caution[results[0].inferred as keyof typeof caution]}</span></div></div>}
  </section>

  <section id="finder" className="finder section-pad"><div className="section-head"><div><span className="kicker">02 / DOMAIN MAP</span><h2>Explore the work,<br/>not the hype.</h2></div><p>Browse common workflows across {domains.length} industries. Rankings are editorial task-fit estimates—not universal benchmark scores.</p></div><div className="domain-tabs" role="tablist">{domains.map(d=><button key={d.id} onClick={()=>setDomain(d.id)} className={domain===d.id?"active":""} role="tab" aria-selected={domain===d.id}><span>{d.icon}</span>{d.name}</button>)}</div><div className="recommend-grid"><div className="domain-card"><div className="domain-title"><span className="domain-icon">{current.icon}</span><div><span>EXPLORE THE DOMAIN</span><h3>{current.name}</h3><p>{current.desc}</p></div></div><div className="areas">{current.areas.map((a,i)=><button key={a}><span>0{i+1}</span>{a}<b>↗</b></button>)}</div><div className="example"><span>EXAMPLE WORKFLOW</span><p>“{current.example}”</p></div></div><div className="winner-card"><div className="winner-top"><span>BEST EDITORIAL FIT</span><span className="score">{scoreFor(ranked[0],domain)} / 100</span></div><div className={`big-mark ${ranked[0].tone}`}>{ranked[0].mark}</div><p className="maker">{ranked[0].maker}</p><h3>{ranked[0].name}</h3><p className="bestfor">{ranked[0].best}</p><div className="why"><span>EVIDENCE SNAPSHOT</span><ul>{ranked[0].proofs.slice(0,2).map(p=><li key={p.label}><a href={p.url} target="_blank" rel="noreferrer">{p.label}: <b>{p.value}</b> · {p.source} ↗</a></li>)}</ul></div><a target="_blank" rel="noreferrer" href={ranked[0].link} className="access">Open official page <span>↗</span></a><p className="micro">Recommendation is not approval for autonomous use.</p></div></div><div className="caution"><span>!</span><div><b>{current.name} safety note</b><p>{caution[domain as keyof typeof caution]}</p></div></div></section>

  <section id="catalog" className="catalog section-pad"><div className="section-head dark"><div><span className="kicker">03 / EVIDENCE LIBRARY · {models.length} MODELS</span><h2>Claims you can<br/><em>open and inspect.</em></h2></div><p>This catalog covers prominent current general-purpose model families and meaningful deployment tiers—not thousands of fine-tunes or deprecated snapshots. Every proof opens its source.</p></div><div className="catalog-tools"><label>⌕<input aria-label="Search models" placeholder="Search models, providers or capabilities" value={query} onChange={e=>setQuery(e.target.value)}/></label><div>{["All","App + API","API","Open weights"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><div className="model-grid">{visible.map((m,i)=><article className="model-card" key={m.id}><div className="model-num">{String(i+1).padStart(2,"0")}<button className={selected.includes(m.id)?"checked":""} onClick={()=>toggleCompare(m.id)} aria-label={`Compare ${m.name}`}>{selected.includes(m.id)?"✓":"+"}</button></div><div className={`model-mark ${m.tone}`}>{m.mark}</div><span className="model-type">{m.type}</span><h3>{m.name}</h3><p className="by">by {m.maker}</p><div className="spec-row"><span><b>{m.context}</b> context</span><span><b>{m.price}</b> / 1M tokens</span></div><div className="tagrow">{m.tags.map(t=><span key={t}>{t}</span>)}</div><dl><div><dt>SHINES AT</dt><dd>{m.best}</dd></div><div><dt>WATCH FOR</dt><dd>{m.limits}</dd></div></dl><div className="card-proofs">{m.proofs.slice(0,2).map(p=><a key={p.label} href={p.url} target="_blank" rel="noreferrer"><b>{p.value}</b><span>{p.label}<small>{p.source} ↗</small></span></a>)}</div><div className="card-foot"><span className={m.access==="Open weights"?"open":""}>{m.access}</span><a href={m.link} target="_blank" rel="noreferrer">{m.access==="Open weights"?"Get weights":"Open"} ↗</a></div></article>)}</div><div className="methodology"><b>How to read the proof</b><p>Benchmark scores are not directly comparable unless the dataset, model version, prompting, tool access, reasoning effort and evaluation harness match. Treat them as evidence of a demonstrated capability—not a guarantee for your task.</p><a href={independent} target="_blank" rel="noreferrer">Cross-check independent model evaluations ↗</a></div></section>

  <section id="compare" className="compare section-pad"><div className="section-head"><div><span className="kicker">04 / EVIDENCE COMPARE</span><h2>Select models.<br/>Inspect the proof.</h2></div><p>Choose up to four from the full catalog. The comparison combines published specifications, editorial task fit and direct links to the underlying evidence.</p></div><div className="select-models"><span>SELECT MODELS ({selected.length}/4)</span><div>{models.map(m=><button key={m.id} className={selected.includes(m.id)?"active":""} onClick={()=>toggleCompare(m.id)}><i>{selected.includes(m.id)?"✓":"+"}</i>{m.name}</button>)}</div></div><div className="compare-wrap detailed"><div className="compare-labels"><b>MODEL</b><span>Context</span><span>Modalities</span><span>Access / license</span><span>{current.name} fit</span><span>Published proof</span><span>Official page</span></div>{selected.map(id=>{const m=models.find(x=>x.id===id)!;const fit=scoreFor(m,domain);return <div className="compare-col" key={id}><div className="compare-model"><span className={`tiny-mark ${m.tone}`}>{m.mark}</span><b>{m.name}</b><button onClick={()=>toggleCompare(id)}>×</button></div><div className="compare-copy"><b>{m.context}</b><small>tokens</small></div><div className="compare-copy">{m.modalities}</div><div className="compare-copy"><b>{m.access}</b><small>{m.license}</small></div><div className="bar-cell"><span style={{width:`${fit}%`}}></span><b>{fit}</b></div><div className="compare-proof">{m.proofs.slice(0,2).map(p=><a href={p.url} target="_blank" rel="noreferrer" key={p.label}><b>{p.value}</b> {p.label} ↗</a>)}</div><div className="access-cell"><a href={m.link} target="_blank" rel="noreferrer">Open source ↗</a></div></div>})}{selected.length===0&&<div className="empty">Choose models above to compare.</div>}</div><p className="compare-note">Comparison domain: <b>{current.name}</b>. Change it in the Domain Map above. Fit scores are Model Atlas editorial estimates; published proof points retain their original source and methodology.</p></section>
  <footer><div className="brand"><span className="brand-mark">M</span><span>Model Atlas</span></div><p>Choose with evidence. Deploy with oversight.</p><div><a href="#top">Back to top ↑</a><span>Research checked · Aug 2026</span></div></footer>
 </main>
}
