import type { Model } from "./types";

export const independent = "https://artificialanalysis.ai/models";
export const models: readonly Model[] = [
  {
    id: "gpt",
    name: "GPT-5.6 Sol",
    maker: "OpenAI",
    mark: "◎",
    tone: "lime",
    type: "Frontier reasoning",
    access: "App + API",
    context: "1.05M",
    price: "$5 / $30",
    modalities: "Text + image input",
    license: "Hosted",
    best: "Complex professional work, production coding, agents and computer use",
    limits:
      "Cloud-hosted; expensive output; no audio/video input; high-stakes facts still require verification.",
    tags: ["Reasoning", "Code", "Vision", "Tools"],
    scores: {
      medical: 94,
      software: 98,
      construction: 94,
      creative: 88,
      research: 96,
    },
    keywords: [
      "code",
      "software",
      "agent",
      "cyber",
      "research",
      "science",
      "cad",
      "construction",
      "spreadsheet",
      "computer use",
    ],
    link: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
    proofs: [
      {
        label: "Professional workflows",
        value: "52.7%",
        note: "Agents’ Last Exam, max reasoning",
        url: "https://openai.com/index/gpt-5-6/",
        source: "OpenAI · self-reported",
      },
      {
        label: "Agentic browsing",
        value: "92.2%",
        note: "BrowseComp with Ultra",
        url: "https://openai.com/index/gpt-5-6/",
        source: "OpenAI · self-reported",
      },
      {
        label: "Published context",
        value: "1.05M",
        note: "128K maximum output",
        url: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
        source: "OpenAI API docs",
      },
    ],
  },
  {
    id: "claude",
    name: "Claude Opus 4.8",
    maker: "Anthropic",
    mark: "A",
    tone: "coral",
    type: "Frontier reasoning",
    access: "App + API",
    context: "200K",
    price: "$5 / $25",
    modalities: "Text + image input",
    license: "Hosted",
    best: "Large codebases, long-form analysis, careful writing and document-heavy work",
    limits:
      "Cloud-hosted; premium price; usage limits and effort settings change latency and cost.",
    tags: ["Reasoning", "Code", "Documents", "Tools"],
    scores: {
      medical: 92,
      software: 97,
      construction: 89,
      creative: 96,
      research: 95,
    },
    keywords: [
      "write",
      "writing",
      "legal",
      "document",
      "codebase",
      "migration",
      "analysis",
      "financial",
      "style",
      "review",
    ],
    link: "https://www.anthropic.com/news/claude-opus-4-8",
    proofs: [
      {
        label: "Coding",
        value: "88.6%",
        note: "SWE-bench Verified",
        url: "https://www.anthropic.com/system-cards",
        source: "Anthropic system card",
      },
      {
        label: "Browser use",
        value: "84.3%",
        note: "BrowseComp, single agent",
        url: "https://www.anthropic.com/system-cards",
        source: "Anthropic system card",
      },
      {
        label: "Self-critique",
        value: "4×",
        note: "Less likely than 4.7 to miss flaws in its code",
        url: "https://www.anthropic.com/news/claude-opus-4-8",
        source: "Anthropic · self-reported",
      },
    ],
  },
  {
    id: "gemini",
    name: "Gemini 3.1 Pro",
    maker: "Google",
    mark: "✦",
    tone: "blue",
    type: "Multimodal frontier",
    access: "App + API",
    context: "1M",
    price: "See current rate card",
    modalities: "Text, image, audio + video",
    license: "Hosted",
    best: "Multimodal research, very long contexts, video/audio and Google workflows",
    limits:
      "Preview/stable variants change; 1M-context retrieval is materially weaker than at 128K in Google’s own MRCR result.",
    tags: ["Vision", "Video", "Long context", "Tools"],
    scores: {
      medical: 95,
      software: 94,
      construction: 97,
      creative: 91,
      research: 98,
    },
    keywords: [
      "video",
      "audio",
      "image",
      "diagram",
      "drawing",
      "blueprint",
      "long document",
      "google",
      "multimodal",
      "lecture",
    ],
    link: "https://deepmind.google/models/model-cards/gemini-3-1-pro/",
    proofs: [
      {
        label: "Science knowledge",
        value: "94.3%",
        note: "GPQA Diamond, no tools",
        url: "https://deepmind.google/models/model-cards/gemini-3-1-pro/",
        source: "Google model card",
      },
      {
        label: "Abstract reasoning",
        value: "77.1%",
        note: "ARC-AGI-2 verified",
        url: "https://deepmind.google/models/model-cards/gemini-3-1-pro/",
        source: "Google model card",
      },
      {
        label: "Multimodal",
        value: "80.5%",
        note: "MMMU-Pro, no tools",
        url: "https://deepmind.google/models/model-cards/gemini-3-1-pro/",
        source: "Google model card",
      },
    ],
  },
  {
    id: "llama",
    name: "Llama 4 Maverick",
    maker: "Meta",
    mark: "∞",
    tone: "violet",
    type: "Open-weight multimodal",
    access: "Open weights",
    context: "1M",
    price: "Infrastructure cost",
    modalities: "Text + image input",
    license: "Llama license",
    best: "Private deployments, customization and high-throughput multimodal applications",
    limits:
      "400B total parameters; self-hosting needs serious hardware, evaluation, security and safety engineering.",
    tags: ["Open weights", "Vision", "Fine-tune"],
    scores: {
      medical: 78,
      software: 87,
      construction: 85,
      creative: 86,
      research: 82,
    },
    keywords: [
      "private",
      "on premise",
      "self host",
      "fine tune",
      "customize",
      "image",
      "high volume",
    ],
    link: "https://ai.meta.com/llama/get-started/",
    proofs: [
      {
        label: "Architecture",
        value: "17B active",
        note: "128 experts; 400B total parameters",
        url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
        source: "Meta release",
      },
      {
        label: "Availability",
        value: "Weights",
        note: "Direct and partner downloads",
        url: "https://ai.meta.com/llama/get-started/",
        source: "Meta documentation",
      },
      {
        label: "Input",
        value: "Multimodal",
        note: "Native text and image understanding",
        url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
        source: "Meta release",
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek R1",
    maker: "DeepSeek",
    mark: "D",
    tone: "blue",
    type: "Open reasoning",
    access: "Open weights",
    context: "128K",
    price: "Infrastructure cost",
    modalities: "Text",
    license: "MIT (base R1)",
    best: "Math, reasoning research and cost-controlled open deployment",
    limits:
      "Older than today’s frontier; large local inference footprint; cited results use the authors’ own evaluation settings.",
    tags: ["Reasoning", "Math", "Open weights"],
    scores: {
      medical: 76,
      software: 91,
      construction: 79,
      creative: 70,
      research: 88,
    },
    keywords: [
      "math",
      "equation",
      "reasoning",
      "open source",
      "self host",
      "research",
      "codeforces",
    ],
    link: "https://github.com/deepseek-ai/DeepSeek-R1",
    proofs: [
      {
        label: "Mathematics",
        value: "97.3%",
        note: "MATH-500 pass@1",
        url: "https://github.com/deepseek-ai/DeepSeek-R1",
        source: "DeepSeek technical report",
      },
      {
        label: "Coding",
        value: "65.9%",
        note: "LiveCodeBench pass@1-CoT",
        url: "https://github.com/deepseek-ai/DeepSeek-R1",
        source: "DeepSeek technical report",
      },
      {
        label: "License",
        value: "MIT",
        note: "Base R1; distilled models inherit base-model terms",
        url: "https://github.com/deepseek-ai/DeepSeek-R1",
        source: "DeepSeek repository",
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral Medium 3.5",
    maker: "Mistral AI",
    mark: "M",
    tone: "coral",
    type: "Open multimodal agent",
    access: "Open weights",
    context: "256K",
    price: "$1.50 / $7.50",
    modalities: "Text + image / OCR",
    license: "Modified MIT",
    best: "Multilingual enterprise agents, coding, OCR and European deployment",
    limits:
      "Modified license needs review; ecosystem and independent evaluation coverage are smaller than for the largest labs.",
    tags: ["Multilingual", "Code", "Open weights"],
    scores: {
      medical: 82,
      software: 92,
      construction: 92,
      creative: 86,
      research: 86,
    },
    keywords: [
      "europe",
      "european",
      "multilingual",
      "french",
      "german",
      "spanish",
      "italian",
      "ocr",
      "document",
      "private",
    ],
    link: "https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",
    proofs: [
      {
        label: "Published context",
        value: "256K",
        note: "Frontier-class multimodal model",
        url: "https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",
        source: "Mistral model card",
      },
      {
        label: "API price / 1M",
        value: "$1.50 / $7.50",
        note: "Input / output at publication",
        url: "https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",
        source: "Mistral documentation",
      },
      {
        label: "Distribution",
        value: "Open weights",
        note: "Modified MIT license",
        url: "https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",
        source: "Mistral model card",
      },
    ],
  },
  {
    id: "qwen",
    name: "Qwen 3.6 35B-A3B",
    maker: "Alibaba Qwen",
    mark: "Q",
    tone: "violet",
    type: "Efficient open agent",
    access: "Open weights",
    context: "256K",
    price: "Infrastructure cost",
    modalities: "Text + image",
    license: "See model license",
    best: "Efficient agentic coding, multilingual and Chinese-language applications",
    limits:
      "Provider benchmarks include internal tests; licensing, regional compliance and deployment controls need review.",
    tags: ["Open weights", "Multilingual", "Code"],
    scores: {
      medical: 79,
      software: 93,
      construction: 84,
      creative: 81,
      research: 87,
    },
    keywords: [
      "chinese",
      "multilingual",
      "coding",
      "efficient",
      "small gpu",
      "open source",
      "agent",
      "self host",
    ],
    link: "https://qwen.ai/blog?id=qwen3.6-35b-a3b",
    proofs: [
      {
        label: "Efficiency",
        value: "3B active",
        note: "35B total MoE parameters",
        url: "https://qwen.ai/blog?id=qwen3.6-35b-a3b",
        source: "Qwen release",
      },
      {
        label: "Context",
        value: "256K",
        note: "Published evaluation setting",
        url: "https://qwen.ai/blog?id=qwen3.6-35b-a3b",
        source: "Qwen release",
      },
      {
        label: "Availability",
        value: "Weights + API",
        note: "Hugging Face, ModelScope and Qwen Studio",
        url: "https://qwen.ai/blog?id=qwen3.6-35b-a3b",
        source: "Qwen release",
      },
    ],
  },
  {
    id: "gemma",
    name: "Gemma 4 31B",
    maker: "Google",
    mark: "G",
    tone: "lime",
    type: "Efficient open multimodal",
    access: "Open weights",
    context: "128K",
    price: "Infrastructure cost",
    modalities: "Text + image",
    license: "Gemma terms",
    best: "Private multimodal apps, research, tuning and consumer-workstation deployment",
    limits:
      "Smaller than frontier hosted models; Google warns of factual errors, bias and weak common-sense reasoning.",
    tags: ["Open weights", "Efficient", "Fine-tune"],
    scores: {
      medical: 84,
      software: 90,
      construction: 87,
      creative: 84,
      research: 85,
    },
    keywords: [
      "local",
      "workstation",
      "fine tune",
      "open model",
      "privacy",
      "image",
      "medical image",
      "efficient",
    ],
    link: "https://ai.google.dev/gemma/docs/core/model_card_4",
    proofs: [
      {
        label: "Knowledge",
        value: "85.2%",
        note: "MMLU-Pro, 31B instruction model",
        url: "https://ai.google.dev/gemma/docs/core/model_card_4",
        source: "Google model card",
      },
      {
        label: "Coding",
        value: "80.0%",
        note: "LiveCodeBench v6",
        url: "https://ai.google.dev/gemma/docs/core/model_card_4",
        source: "Google model card",
      },
      {
        label: "Medical multimodal",
        value: "61.3%",
        note: "MedXPertQA-MM",
        url: "https://ai.google.dev/gemma/docs/core/model_card_4",
        source: "Google model card",
      },
    ],
  },
  {
    id: "gpt-terra",
    name: "GPT-5.6 Terra",
    maker: "OpenAI",
    mark: "◎",
    tone: "lime",
    type: "Balanced reasoning",
    access: "API",
    context: "1.05M",
    price: "$2 / $12",
    modalities: "Text + image input",
    license: "Hosted",
    best: "Everyday production agents that need strong reasoning at lower cost than Sol",
    limits:
      "Cloud-only; high-context requests cost more; still needs workload-specific evaluation.",
    tags: ["Reasoning", "Code", "Tools", "Balanced"],
    scores: {
      medical: 91,
      software: 95,
      construction: 92,
      creative: 87,
      research: 93,
    },
    keywords: [
      "balanced",
      "production",
      "agent",
      "code",
      "cost",
      "volume",
      "automation",
    ],
    link: "https://developers.openai.com/api/docs/models",
    proofs: [
      {
        label: "Professional workflows",
        value: "50.4%",
        note: "Agents’ Last Exam",
        url: "https://openai.com/index/gpt-5-6/",
        source: "OpenAI · self-reported",
      },
      {
        label: "Published context",
        value: "1.05M",
        note: "128K maximum output",
        url: "https://developers.openai.com/api/docs/models",
        source: "OpenAI API docs",
      },
    ],
  },
  {
    id: "gpt-luna",
    name: "GPT-5.6 Luna",
    maker: "OpenAI",
    mark: "◎",
    tone: "lime",
    type: "Economical reasoning",
    access: "API",
    context: "1.05M",
    price: "$0.20 / $1.20",
    modalities: "Text + image input",
    license: "Hosted",
    best: "High-volume classification, extraction, subagents and cost-sensitive automation",
    limits:
      "Less capable than Sol on the hardest work; output price can still dominate long generations.",
    tags: ["Efficient", "Code", "Tools", "High volume"],
    scores: {
      medical: 87,
      software: 92,
      construction: 89,
      creative: 84,
      research: 89,
    },
    keywords: [
      "cheap",
      "cost",
      "volume",
      "classify",
      "extract",
      "subagent",
      "fast",
    ],
    link: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
    proofs: [
      {
        label: "Professional workflows",
        value: "50.3%",
        note: "Agents’ Last Exam",
        url: "https://openai.com/index/gpt-5-6/",
        source: "OpenAI · self-reported",
      },
      {
        label: "API price / 1M",
        value: "$0.20 / $1.20",
        note: "Input / output",
        url: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        source: "OpenAI API docs",
      },
    ],
  },
  {
    id: "fable",
    name: "Claude Fable 5",
    maker: "Anthropic",
    mark: "A",
    tone: "coral",
    type: "Safeguarded frontier",
    access: "App + API",
    context: "200K",
    price: "$10 / $50",
    modalities: "Text + image input",
    license: "Hosted",
    best: "The most difficult coding, research, knowledge-work and vision tasks",
    limits:
      "Very expensive; conservative safeguards can route some requests to Opus 4.8; not an autonomous authority.",
    tags: ["Frontier", "Reasoning", "Code", "Vision"],
    scores: {
      medical: 96,
      software: 99,
      construction: 93,
      creative: 97,
      research: 99,
    },
    keywords: [
      "hardest",
      "complex",
      "frontier",
      "science",
      "research",
      "code",
      "vision",
      "professional",
    ],
    link: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
    proofs: [
      {
        label: "General availability",
        value: "Fable 5",
        note: "Safeguarded Mythos-class model",
        url: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
        source: "Anthropic release",
      },
      {
        label: "API price / 1M",
        value: "$10 / $50",
        note: "Input / output",
        url: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
        source: "Anthropic release",
      },
    ],
  },
  {
    id: "sonnet",
    name: "Claude Sonnet 5",
    maker: "Anthropic",
    mark: "A",
    tone: "coral",
    type: "Scaled frontier",
    access: "App + API",
    context: "200K",
    price: "$2 / $10*",
    modalities: "Text + image input",
    license: "Hosted",
    best: "Coding, agents and professional work at production scale",
    limits:
      "Introductory pricing ends Aug 31, 2026; hosted only; complex work may still favor Fable or Opus.",
    tags: ["Code", "Agents", "Documents", "Balanced"],
    scores: {
      medical: 91,
      software: 97,
      construction: 91,
      creative: 94,
      research: 94,
    },
    keywords: [
      "code",
      "agent",
      "professional",
      "scale",
      "document",
      "balanced",
      "production",
    ],
    link: "https://www.anthropic.com/news/claude-sonnet-5",
    proofs: [
      {
        label: "Launch focus",
        value: "Coding + agents",
        note: "Frontier performance at scale",
        url: "https://www.anthropic.com/news/claude-sonnet-5",
        source: "Anthropic release",
      },
      {
        label: "Intro price / 1M",
        value: "$2 / $10",
        note: "Through Aug 31, 2026",
        url: "https://www.anthropic.com/news/claude-sonnet-5",
        source: "Anthropic release",
      },
    ],
  },
  {
    id: "gemini-flash",
    name: "Gemini 3.6 Flash",
    maker: "Google",
    mark: "✦",
    tone: "blue",
    type: "Fast multimodal agent",
    access: "API",
    context: "1M",
    price: "See rate card",
    modalities: "Text, image, audio + video",
    license: "Hosted",
    best: "Fast multimodal automation, coding loops and high-volume subagents",
    limits:
      "Flash prioritizes speed and efficiency over peak Pro capability; availability and rate cards change.",
    tags: ["Fast", "Vision", "Video", "Tools"],
    scores: {
      medical: 89,
      software: 94,
      construction: 94,
      creative: 89,
      research: 92,
    },
    keywords: [
      "fast",
      "video",
      "audio",
      "image",
      "agent",
      "high volume",
      "google",
      "multimodal",
    ],
    link: "https://ai.google.dev/gemini-api/docs/changelog",
    proofs: [
      {
        label: "Availability",
        value: "GA",
        note: "Stable release July 2026",
        url: "https://ai.google.dev/gemini-api/docs/changelog",
        source: "Google API changelog",
      },
      {
        label: "Input limit",
        value: "1M",
        note: "Flash family multimodal context",
        url: "https://ai.google.dev/gemini-api/docs/models",
        source: "Google API docs",
      },
    ],
  },
  {
    id: "grok",
    name: "Grok 4.20",
    maker: "xAI",
    mark: "X",
    tone: "violet",
    type: "Fast agentic model",
    access: "App + API",
    context: "2M",
    price: "See rate card",
    modalities: "Text + image input",
    license: "Hosted",
    best: "Fast agents, tool calling, current-events workflows and X-native research",
    limits:
      "Hosted only; social-web grounding can amplify noisy or low-quality sources; verify citations.",
    tags: ["Agents", "Search", "Tools", "Fast"],
    scores: {
      medical: 86,
      software: 94,
      construction: 87,
      creative: 89,
      research: 92,
    },
    keywords: [
      "x",
      "twitter",
      "social",
      "current events",
      "search",
      "agent",
      "fast",
      "tool",
    ],
    link: "https://docs.x.ai/developers/models/grok-4.20",
    proofs: [
      {
        label: "Model focus",
        value: "Agentic",
        note: "High speed and tool calling",
        url: "https://docs.x.ai/developers/models/grok-4.20",
        source: "xAI documentation",
      },
      {
        label: "Safety record",
        value: "System card",
        note: "Published April 2026",
        url: "https://data.x.ai/2026-04-07-grok-4-20-model-card.pdf",
        source: "xAI system card",
      },
    ],
  },
  {
    id: "deepseek-v4",
    name: "DeepSeek V4 Pro",
    maker: "DeepSeek",
    mark: "D",
    tone: "blue",
    type: "Low-cost frontier API",
    access: "API",
    context: "1M",
    price: "$0.435 / $0.87",
    modalities: "Text",
    license: "Hosted API",
    best: "Extremely low-cost reasoning, coding, long contexts and high-volume tool use",
    limits:
      "Regional governance and data-handling need review; official pricing can change; text-only input.",
    tags: ["Reasoning", "Code", "Long context", "Low cost"],
    scores: {
      medical: 87,
      software: 96,
      construction: 86,
      creative: 80,
      research: 94,
    },
    keywords: [
      "cheap",
      "low cost",
      "code",
      "reasoning",
      "long context",
      "math",
      "api",
    ],
    link: "https://api-docs.deepseek.com/quick_start/pricing/",
    proofs: [
      {
        label: "Published context",
        value: "1M",
        note: "384K maximum output",
        url: "https://api-docs.deepseek.com/quick_start/pricing/",
        source: "DeepSeek API docs",
      },
      {
        label: "API price / 1M",
        value: "$0.435 / $0.87",
        note: "Cache-miss input / output",
        url: "https://api-docs.deepseek.com/quick_start/pricing/",
        source: "DeepSeek API docs",
      },
    ],
  },
  {
    id: "glm",
    name: "GLM-5.2",
    maker: "Z.ai",
    mark: "Z",
    tone: "lime",
    type: "Open long-horizon model",
    access: "Open weights",
    context: "1M",
    price: "Infrastructure cost",
    modalities: "Text",
    license: "MIT",
    best: "Very long coding-agent trajectories, research and sovereign open deployment",
    limits:
      "Massive serving footprint; provider comparisons use specific harnesses and judging models.",
    tags: ["Open weights", "Code", "Long context", "Agents"],
    scores: {
      medical: 84,
      software: 97,
      construction: 87,
      creative: 80,
      research: 95,
    },
    keywords: [
      "long horizon",
      "code",
      "agent",
      "open source",
      "mit",
      "research",
      "1m",
      "sovereign",
    ],
    link: "https://z.ai/blog/glm-5.2",
    proofs: [
      {
        label: "Terminal work",
        value: "81.0",
        note: "Terminal-Bench 2.1",
        url: "https://z.ai/blog/glm-5.2",
        source: "Z.ai · self-reported",
      },
      {
        label: "Published context",
        value: "1M",
        note: "MIT open-source weights",
        url: "https://z.ai/blog/glm-5.2",
        source: "Z.ai release",
      },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax M3",
    maker: "MiniMax",
    mark: "M3",
    tone: "coral",
    type: "Open multimodal frontier",
    access: "Open weights",
    context: "1M",
    price: "Infrastructure cost",
    modalities: "Text, image + video",
    license: "See model license",
    best: "Open multimodal agents, coding, office workflows and computer use",
    limits:
      "Very new; independent evidence is limited; large-scale self-hosting remains complex.",
    tags: ["Open weights", "Vision", "Video", "Agents"],
    scores: {
      medical: 84,
      software: 95,
      construction: 92,
      creative: 91,
      research: 91,
    },
    keywords: [
      "video",
      "image",
      "computer use",
      "open source",
      "coding",
      "office",
      "agent",
      "1m",
    ],
    link: "https://www.minimax.io/blog/minimax-m3",
    proofs: [
      {
        label: "Published context",
        value: "1M",
        note: "Native multimodality",
        url: "https://www.minimax.io/blog/minimax-m3",
        source: "MiniMax release",
      },
      {
        label: "Input",
        value: "Image + video",
        note: "Also supports computer use",
        url: "https://www.minimax.io/blog/minimax-m3",
        source: "MiniMax release",
      },
    ],
  },
  {
    id: "command",
    name: "Command A+",
    maker: "Cohere",
    mark: "C",
    tone: "blue",
    type: "Sovereign enterprise agent",
    access: "Open weights",
    context: "128K",
    price: "Infrastructure cost",
    modalities: "Text + image + tools",
    license: "Apache 2.0",
    best: "Air-gapped enterprise RAG, multilingual agents and regulated infrastructure",
    limits:
      "218B total parameters; minimum practical hardware is substantial; benchmark results are provider-reported.",
    tags: ["Open weights", "RAG", "Multilingual", "Agents"],
    scores: {
      medical: 88,
      software: 91,
      construction: 90,
      creative: 84,
      research: 91,
    },
    keywords: [
      "rag",
      "citation",
      "sovereign",
      "air gap",
      "government",
      "regulated",
      "multilingual",
      "enterprise",
    ],
    link: "https://cohere.com/blog/command-a-plus",
    proofs: [
      {
        label: "Languages",
        value: "48",
        note: "Multilingual support",
        url: "https://cohere.com/blog/command-a-plus",
        source: "Cohere release",
      },
      {
        label: "Architecture",
        value: "25B active",
        note: "218B total; Apache 2.0",
        url: "https://cohere.com/blog/command-a-plus",
        source: "Cohere release",
      },
    ],
  },
  {
    id: "granite",
    name: "Granite 4.0 H Small",
    maker: "IBM",
    mark: "I",
    tone: "violet",
    type: "Efficient enterprise open",
    access: "Open weights",
    context: "128K",
    price: "Infrastructure cost",
    modalities: "Text",
    license: "Apache 2.0",
    best: "Enterprise RAG, agents, function calling and memory-efficient private deployment",
    limits:
      "Not a frontier reasoning model; hybrid architecture support varies across inference runtimes.",
    tags: ["Open weights", "RAG", "Efficient", "Enterprise"],
    scores: {
      medical: 80,
      software: 87,
      construction: 83,
      creative: 75,
      research: 84,
    },
    keywords: [
      "ibm",
      "enterprise",
      "rag",
      "function calling",
      "efficient",
      "private",
      "iso",
      "edge",
    ],
    link: "https://www.ibm.com/granite/docs/models/granite",
    proofs: [
      {
        label: "Memory",
        value: "70% lower",
        note: "Than similar models, per IBM",
        url: "https://www.ibm.com/granite/docs/models/granite",
        source: "IBM documentation",
      },
      {
        label: "Architecture",
        value: "32B / 9B",
        note: "Total / activated parameters",
        url: "https://www.ibm.com/granite/docs/models/granite",
        source: "IBM documentation",
      },
    ],
  },
  {
    id: "phi",
    name: "Phi-4 Multimodal",
    maker: "Microsoft",
    mark: "P",
    tone: "lime",
    type: "Small on-device model",
    access: "Open weights",
    context: "128K",
    price: "Infrastructure cost",
    modalities: "Text, image + audio",
    license: "MIT",
    best: "On-device and edge multimodal applications with limited hardware",
    limits:
      "A 5.6B small model cannot match frontier models on the hardest reasoning or agentic tasks.",
    tags: ["Open weights", "On-device", "Audio", "Vision"],
    scores: {
      medical: 77,
      software: 83,
      construction: 82,
      creative: 80,
      research: 79,
    },
    keywords: [
      "edge",
      "device",
      "small",
      "mobile",
      "audio",
      "speech",
      "vision",
      "offline",
    ],
    link: "https://azure.microsoft.com/en-us/blog/empowering-innovation-the-next-generation-of-the-phi-family/",
    proofs: [
      {
        label: "Model size",
        value: "5.6B",
        note: "Unified speech, vision and text",
        url: "https://azure.microsoft.com/en-us/blog/empowering-innovation-the-next-generation-of-the-phi-family/",
        source: "Microsoft release",
      },
      {
        label: "Deployment",
        value: "Edge",
        note: "Designed for low-latency local use",
        url: "https://azure.microsoft.com/en-us/products/phi/",
        source: "Microsoft documentation",
      },
    ],
  },
  {
    id: "nova",
    name: "Amazon Nova Premier",
    maker: "AWS",
    mark: "N",
    tone: "coral",
    type: "Bedrock multimodal teacher",
    access: "API",
    context: "1M",
    price: "See Bedrock pricing",
    modalities: "Text, image + video",
    license: "Hosted",
    best: "AWS-native complex workflows, multimodal documents and model distillation",
    limits:
      "AWS marks this version legacy with EOL September 14, 2026; plan migration before new production adoption.",
    tags: ["AWS", "Vision", "Video", "Agents"],
    scores: {
      medical: 84,
      software: 88,
      construction: 91,
      creative: 86,
      research: 89,
    },
    keywords: [
      "aws",
      "bedrock",
      "distill",
      "video",
      "image",
      "document",
      "agent",
      "enterprise",
    ],
    link: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",
    proofs: [
      {
        label: "Published context",
        value: "1M",
        note: "25K maximum output",
        url: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",
        source: "AWS documentation",
      },
      {
        label: "Lifecycle",
        value: "Legacy",
        note: "EOL Sep 14, 2026",
        url: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-amazon-nova-premier.html",
        source: "AWS documentation",
      },
    ],
  },
  {
    id: "sonar",
    name: "Sonar Pro",
    maker: "Perplexity",
    mark: "S",
    tone: "blue",
    type: "Search-grounded model",
    access: "API",
    context: "200K",
    price: "$3 / $15 + search",
    modalities: "Text + web search",
    license: "Hosted",
    best: "Current, citation-heavy research and complex multi-step web questions",
    limits:
      "Non-reasoning model; answer quality depends on retrieved sources; search requests add cost.",
    tags: ["Search", "Citations", "Research", "RAG"],
    scores: {
      medical: 88,
      software: 86,
      construction: 84,
      creative: 82,
      research: 96,
    },
    keywords: [
      "latest",
      "current",
      "web",
      "source",
      "citation",
      "search",
      "news",
      "research",
    ],
    link: "https://docs.perplexity.ai/docs/sonar/models/sonar-pro",
    proofs: [
      {
        label: "Search depth",
        value: "2×",
        note: "More results than standard Sonar",
        url: "https://docs.perplexity.ai/docs/sonar/models/sonar-pro",
        source: "Perplexity documentation",
      },
      {
        label: "Published context",
        value: "200K",
        note: "Complex multi-step Q&A",
        url: "https://docs.perplexity.ai/docs/sonar/models/sonar-pro",
        source: "Perplexity documentation",
      },
    ],
  },
  {
    id: "nemotron",
    name: "Nemotron 3 Ultra",
    maker: "NVIDIA",
    mark: "N",
    tone: "violet",
    type: "Open enterprise reasoning",
    access: "Open weights",
    context: "1M",
    price: "Infrastructure cost",
    modalities: "Text",
    license: "NVIDIA Open Model",
    best: "Open enterprise agents, reasoning and long-context GPU-optimized deployment",
    limits:
      "Large 550B-total MoE model; infrastructure-intensive; use-case fit must be evaluated on your own stack.",
    tags: ["Open weights", "Agents", "Long context", "Enterprise"],
    scores: {
      medical: 83,
      software: 92,
      construction: 84,
      creative: 78,
      research: 92,
    },
    keywords: [
      "nvidia",
      "gpu",
      "enterprise",
      "open source",
      "long context",
      "agent",
      "reasoning",
    ],
    link: "https://research.nvidia.com/labs/nemotron/",
    proofs: [
      {
        label: "Architecture",
        value: "550B / 55B",
        note: "Total / active parameters",
        url: "https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf",
        source: "NVIDIA report",
      },
      {
        label: "Long context",
        value: "1M",
        note: "94.7 RULER in provider report",
        url: "https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf",
        source: "NVIDIA · self-reported",
      },
    ],
  },
];
